In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
data = pd.read_csv('./l34.csv')
data.head()

   Basket            Item
0       1          shrimp
1       1         almonds
2       1         avocado
3       1  vegetables mix
4       1    green grapes

In [3]:
data.columns

Index(['Basket', 'Item'], dtype='object')

In [4]:
data.Item.unique()

array(['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes',
       'whole weat flour', 'yams', 'cottage cheese', 'energy drink',
       'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad',
       'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie',
       'spinach', 'olive oil', 'burgers', 'meatballs', 'eggs', 'chutney',
       'turkey', 'milk', 'energy bar', 'whole wheat rice',
       'whole wheat pasta', 'french fries', 'soup', 'light cream',
       'shallot', 'frozen vegetables', 'spaghetti', 'pet food', 'cookies',
       'cooking oil', 'champagne', 'chocolate', 'chicken', 'oil',
       'fresh tuna', 'tomatoes', 'black tea', 'extra dark chocolate',
       'protein bar', 'red wine', 'pasta', 'pepper', 'shampoo', 'rice',
       'sparkling water', 'ham', 'body spray', 'pancakes',
       'grated cheese', 'white wine', 'toothpaste', 'parmesan cheese',
       'fresh bread', 'ground beef', 'escalope', 'herb & pepper',
       'tomato sauce', 'magazines', 'strawberries', 'strong cheese',
       'pickles', 'cake', 'hot dogs', 'brownies', 'cereals',
       'clothes accessories', 'bug spray', 'muffins', 'light mayo',
       'gums', 'soda', 'cider', 'corn', 'yogurt cake', 'mint', 'butter',
       'asparagus', 'french wine', 'salt', 'tea', 'barbecue sauce',
       'mayonnaise', 'zucchini', 'carrots', 'mushroom cream sauce',
       'candy bars', 'chili', 'mashed potato', 'nonfat milk',
       'water spray', 'chocolate bread', 'mint green tea', 'eggplant',
       'blueberries', 'bacon', 'fromage blanc', 'gluten free bar',
       'dessert wine', 'flax seed', 'hand protein bar', 'sandwich',
       'babies food', 'melons', 'cauliflower', 'green beans', 'ketchup',
       'bramble', 'burger sauce', 'oatmeal', ' asparagus', 'cream',
       'napkins'], dtype=object)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29363 entries, 0 to 29362
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Basket  29363 non-null  int64
 1   Item    29363 non-null  object
dtypes: int64(1), object(1)
memory usage: 458.9+ KB

In [8]:
data_encoded = data.pivot_table(index="Basket" , columns="Item" , aggfunc=lambda x:1 , fill_value = 0)
data_encoded = data_encoded.astype(bool)

In [9]:
freq_items = apriori(data_encoded , min_support=0.05 , use_colnames=True)
rules = association_rules(freq_items , metric="lift" , min_threshold= 1)
rules = rules.sort_values(['confidence','lift'] , ascending=[False,False])
print(freq_items)
rules.head()

     support                    itemsets
0   0.087188                   (burgers)
1   0.081056                      (cake)
2   0.059992                   (chicken)
3   0.163845                 (chocolate)
4   0.080389                   (cookies)
5   0.051060               (cooking oil)
6   0.179709                      (eggs)
7   0.079323                  (escalope)
8   0.170911              (french fries)
9   0.063325           (frozen smoothie)
10  0.095321         (frozen vegetables)
11  0.052393             (grated cheese)
12  0.132116                 (green tea)
13  0.098254               (ground beef)
14  0.076523            (low fat yogurt)
15  0.129583                      (milk)
16  0.238368             (mineral water)
17  0.065858                 (olive oil)
18  0.095054                  (pancakes)
19  0.071457                    (shrimp)
20  0.050527                      (soup)
21  0.174110                 (spaghetti)
22  0.068391                  (tomatoes)
23  0.062525                    (turkey)
24  0.058526          (whole wheat rice)
25  0.052660  (mineral water, chocolate)
26  0.050927       (mineral water, eggs)
27  0.059725  (spaghetti, mineral water)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
4,(spaghetti),(mineral water),0.174110,0.238368,0.059725,0.343032,1.439085,1.0,0.018223,1.159314,0.369437,0.169312,0.137421,0.296796
1,(chocolate),(mineral water),0.163845,0.238368,0.052660,0.321400,1.348332,1.0,0.013604,1.122357,0.308965,0.150648,0.109018,0.271158
3,(eggs),(mineral water),0.179709,0.238368,0.050927,0.283383,1.188845,1.0,0.008090,1.062815,0.193648,0.138707,0.059103,0.248515
5,(mineral water),(spaghetti),0.238368,0.174110,0.059725,0.250559,1.439085,1.0,0.018223,1.102008,0.400606,0.169312,0.092566,0.296796
0,(mineral water),(chocolate),0.238368,0.163845,0.052660,0.220917,1.348332,1.0,0.013604,1.073256,0.339197,0.150648,0.068256,0.271158